import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the AND Digital Coding Test v0.1
        </h1>

        

        <div className={styles.grid}>
         

          <div className={styles.card}>
            <h2>Rules</h2>
            <p>This is a coding test for AND Digital. You may play with this site before the test begins.</p>
          </div>

          <div className={styles.card}>
            <h2>Guidence</h2>
            <p>You will be asked to pull data from the site's API during the test using any coding environment / language you desire</p>
          </div>

          <div  className={styles.card}>
            <h2>Pre-work</h2>
            <p>
              You can come to the test with a fully working application, but will be expected to make changes in it under test conditions
            </p>
          </div>

          <a href="/api/a" className={styles.card}>
            <h2>Example API endpoint</h2>
            <p>See some data being returned by the endpoint.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
